### ISSUE TITLE
obj number doesn't match with number of items

### ISSUE THREAD

**Issue by EquilibriaW** [qq456cvb/PACE#2]
Hi, everything past obj 000545 is for an articulated object, but there are 71 distinct instances of articulated objects and 576 objects in total. However, since there should be one to one matching between obj and distinct object instance for non-articulated objects, shouldn't this imply that there are 617 objects? Or do some of the non-articulated objects also have multiple obj files which correspond to them?

**Comment by qq456cvb** [comment]
Hi thanks for the interest, actually there are some objects that only lives in the model database but do not have a real world test image. Please check our updated paper and repo for more details.
