### ISSUE TITLE
OneDrive link broken

### ISSUE THREAD

**Issue by alexanderswerdlow** [qq456cvb/PACE#3]
Hi,

It appears that the OneDrive link is down.

Thanks!

<img width="1260" alt="image" src="https://github.com/qq456cvb/PACE/assets/35648800/645c78ae-7fb9-41f9-b23f-d29793bb0210">

**Comment by qq456cvb** [comment]
Thanks for catching this, we are uploading a newer version (with all the data including category-level objects) to hugging face. Stay tuned, it will be released in July mid.

**Comment by qq456cvb** [comment]
Hi we have uploaded the full dataset on huggingface,. Thanks for your patience!
