### ISSUE TITLE
Are camera pose also released in the groundtruth annotation?

### ISSUE THREAD

**Issue by yangyi02** [qq456cvb/PACE#6]
Hi, thanks for releasing this dataset.

May I ask if the camera pose is also released? If so, where can I find them?

Thanks.

**Comment by qq456cvb** [comment]
An easy way is to use the inverse of an annotated static object. Since our object annotation is in the camera frame, so the camera pose is just the inverse of it.

**Comment by yangyi02** [comment]
I thought your object pose annotation is the transformation of current frame object pose w.r.t. the CAD coordinate coordinate framework. And different objects may have different canonical coordinate framework, hence inverse of different static objects may give different poses.

Am I interpreting wrong here?

**Comment by qq456cvb** [comment]
It is not, actually the object pose is the transformation of current object w.r.t. the current camera frames. In other words, it is in camera frame rather than the world frame.
